/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DirectRouteImport } from './routes/direct'
import { Route as FeedRouteImport } from './routes/_feed'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DirectIndexRouteImport } from './routes/direct/index'
import { Route as FeedIndexRouteImport } from './routes/_feed/index'
import { Route as StoriesUsernameRouteImport } from './routes/stories.$username'
import { Route as SettingsSavedRouteImport } from './routes/settings/saved'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsEditProfileRouteImport } from './routes/settings/edit-profile'
import { Route as SettingsAccountPrivacyRouteImport } from './routes/settings/account-privacy'
import { Route as PPostIdRouteImport } from './routes/p.$postId'
import { Route as DirectInboxRouteImport } from './routes/direct/inbox'
import { Route as DirectConversationIdRouteImport } from './routes/direct/$conversationId'
import { Route as ExplorePPostIdModalRouteImport } from './routes/explore/p.$postId.modal'
import { Route as FeedStoriesUsernameModalRouteImport } from './routes/_feed/stories.$username.modal'
import { Route as FeedPPostIdModalRouteImport } from './routes/_feed/p.$postId.modal'
import { Route as UsernamePPostIdModalRouteImport } from './routes/$username/p.$postId.modal'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectRoute = DirectRouteImport.update({
  id: '/direct',
  path: '/direct',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/_feed',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const DirectIndexRoute = DirectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DirectRoute,
} as any)
const FeedIndexRoute = FeedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeedRoute,
} as any)
const StoriesUsernameRoute = StoriesUsernameRouteImport.update({
  id: '/stories/$username',
  path: '/stories/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSavedRoute = SettingsSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEditProfileRoute = SettingsEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountPrivacyRoute = SettingsAccountPrivacyRouteImport.update({
  id: '/account-privacy',
  path: '/account-privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const PPostIdRoute = PPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectInboxRoute = DirectInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DirectRoute,
} as any)
const DirectConversationIdRoute = DirectConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => DirectRoute,
} as any)
const ExplorePPostIdModalRoute = ExplorePPostIdModalRouteImport.update({
  id: '/p/$postId/modal',
  path: '/p/$postId/modal',
  getParentRoute: () => ExploreRoute,
} as any)
const FeedStoriesUsernameModalRoute =
  FeedStoriesUsernameModalRouteImport.update({
    id: '/stories/$username/modal',
    path: '/stories/$username/modal',
    getParentRoute: () => FeedRoute,
  } as any)
const FeedPPostIdModalRoute = FeedPPostIdModalRouteImport.update({
  id: '/p/$postId/modal',
  path: '/p/$postId/modal',
  getParentRoute: () => FeedRoute,
} as any)
const UsernamePPostIdModalRoute = UsernamePPostIdModalRouteImport.update({
  id: '/p/$postId/modal',
  path: '/p/$postId/modal',
  getParentRoute: () => UsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$username': typeof UsernameRouteWithChildren
  '/': typeof FeedIndexRoute
  '/direct': typeof DirectRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/reels': typeof ReelsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/direct/$conversationId': typeof DirectConversationIdRoute
  '/direct/inbox': typeof DirectInboxRoute
  '/p/$postId': typeof PPostIdRoute
  '/settings/account-privacy': typeof SettingsAccountPrivacyRoute
  '/settings/edit-profile': typeof SettingsEditProfileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/saved': typeof SettingsSavedRoute
  '/stories/$username': typeof StoriesUsernameRoute
  '/direct/': typeof DirectIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/$username/p/$postId/modal': typeof UsernamePPostIdModalRoute
  '/p/$postId/modal': typeof FeedPPostIdModalRoute
  '/stories/$username/modal': typeof FeedStoriesUsernameModalRoute
  '/explore/p/$postId/modal': typeof ExplorePPostIdModalRoute
}
export interface FileRoutesByTo {
  '/$username': typeof UsernameRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/reels': typeof ReelsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/direct/$conversationId': typeof DirectConversationIdRoute
  '/direct/inbox': typeof DirectInboxRoute
  '/p/$postId': typeof PPostIdRoute
  '/settings/account-privacy': typeof SettingsAccountPrivacyRoute
  '/settings/edit-profile': typeof SettingsEditProfileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/saved': typeof SettingsSavedRoute
  '/stories/$username': typeof StoriesUsernameRoute
  '/': typeof FeedIndexRoute
  '/direct': typeof DirectIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/$username/p/$postId/modal': typeof UsernamePPostIdModalRoute
  '/p/$postId/modal': typeof FeedPPostIdModalRoute
  '/stories/$username/modal': typeof FeedStoriesUsernameModalRoute
  '/explore/p/$postId/modal': typeof ExplorePPostIdModalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$username': typeof UsernameRouteWithChildren
  '/_feed': typeof FeedRouteWithChildren
  '/direct': typeof DirectRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/reels': typeof ReelsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/direct/$conversationId': typeof DirectConversationIdRoute
  '/direct/inbox': typeof DirectInboxRoute
  '/p/$postId': typeof PPostIdRoute
  '/settings/account-privacy': typeof SettingsAccountPrivacyRoute
  '/settings/edit-profile': typeof SettingsEditProfileRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/saved': typeof SettingsSavedRoute
  '/stories/$username': typeof StoriesUsernameRoute
  '/_feed/': typeof FeedIndexRoute
  '/direct/': typeof DirectIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/$username/p/$postId/modal': typeof UsernamePPostIdModalRoute
  '/_feed/p/$postId/modal': typeof FeedPPostIdModalRoute
  '/_feed/stories/$username/modal': typeof FeedStoriesUsernameModalRoute
  '/explore/p/$postId/modal': typeof ExplorePPostIdModalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$username'
    | '/'
    | '/direct'
    | '/explore'
    | '/reels'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/direct/$conversationId'
    | '/direct/inbox'
    | '/p/$postId'
    | '/settings/account-privacy'
    | '/settings/edit-profile'
    | '/settings/notifications'
    | '/settings/saved'
    | '/stories/$username'
    | '/direct/'
    | '/settings/'
    | '/$username/p/$postId/modal'
    | '/p/$postId/modal'
    | '/stories/$username/modal'
    | '/explore/p/$postId/modal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$username'
    | '/explore'
    | '/reels'
    | '/sign-in'
    | '/sign-up'
    | '/direct/$conversationId'
    | '/direct/inbox'
    | '/p/$postId'
    | '/settings/account-privacy'
    | '/settings/edit-profile'
    | '/settings/notifications'
    | '/settings/saved'
    | '/stories/$username'
    | '/'
    | '/direct'
    | '/settings'
    | '/$username/p/$postId/modal'
    | '/p/$postId/modal'
    | '/stories/$username/modal'
    | '/explore/p/$postId/modal'
  id:
    | '__root__'
    | '/$username'
    | '/_feed'
    | '/direct'
    | '/explore'
    | '/reels'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/direct/$conversationId'
    | '/direct/inbox'
    | '/p/$postId'
    | '/settings/account-privacy'
    | '/settings/edit-profile'
    | '/settings/notifications'
    | '/settings/saved'
    | '/stories/$username'
    | '/_feed/'
    | '/direct/'
    | '/settings/'
    | '/$username/p/$postId/modal'
    | '/_feed/p/$postId/modal'
    | '/_feed/stories/$username/modal'
    | '/explore/p/$postId/modal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UsernameRoute: typeof UsernameRouteWithChildren
  FeedRoute: typeof FeedRouteWithChildren
  DirectRoute: typeof DirectRouteWithChildren
  ExploreRoute: typeof ExploreRouteWithChildren
  ReelsRoute: typeof ReelsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  PPostIdRoute: typeof PPostIdRoute
  StoriesUsernameRoute: typeof StoriesUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direct': {
      id: '/direct'
      path: '/direct'
      fullPath: '/direct'
      preLoaderRoute: typeof DirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_feed': {
      id: '/_feed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/direct/': {
      id: '/direct/'
      path: '/'
      fullPath: '/direct/'
      preLoaderRoute: typeof DirectIndexRouteImport
      parentRoute: typeof DirectRoute
    }
    '/_feed/': {
      id: '/_feed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FeedIndexRouteImport
      parentRoute: typeof FeedRoute
    }
    '/stories/$username': {
      id: '/stories/$username'
      path: '/stories/$username'
      fullPath: '/stories/$username'
      preLoaderRoute: typeof StoriesUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/saved': {
      id: '/settings/saved'
      path: '/saved'
      fullPath: '/settings/saved'
      preLoaderRoute: typeof SettingsSavedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/edit-profile': {
      id: '/settings/edit-profile'
      path: '/edit-profile'
      fullPath: '/settings/edit-profile'
      preLoaderRoute: typeof SettingsEditProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account-privacy': {
      id: '/settings/account-privacy'
      path: '/account-privacy'
      fullPath: '/settings/account-privacy'
      preLoaderRoute: typeof SettingsAccountPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/p/$postId': {
      id: '/p/$postId'
      path: '/p/$postId'
      fullPath: '/p/$postId'
      preLoaderRoute: typeof PPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direct/inbox': {
      id: '/direct/inbox'
      path: '/inbox'
      fullPath: '/direct/inbox'
      preLoaderRoute: typeof DirectInboxRouteImport
      parentRoute: typeof DirectRoute
    }
    '/direct/$conversationId': {
      id: '/direct/$conversationId'
      path: '/$conversationId'
      fullPath: '/direct/$conversationId'
      preLoaderRoute: typeof DirectConversationIdRouteImport
      parentRoute: typeof DirectRoute
    }
    '/explore/p/$postId/modal': {
      id: '/explore/p/$postId/modal'
      path: '/p/$postId/modal'
      fullPath: '/explore/p/$postId/modal'
      preLoaderRoute: typeof ExplorePPostIdModalRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/_feed/stories/$username/modal': {
      id: '/_feed/stories/$username/modal'
      path: '/stories/$username/modal'
      fullPath: '/stories/$username/modal'
      preLoaderRoute: typeof FeedStoriesUsernameModalRouteImport
      parentRoute: typeof FeedRoute
    }
    '/_feed/p/$postId/modal': {
      id: '/_feed/p/$postId/modal'
      path: '/p/$postId/modal'
      fullPath: '/p/$postId/modal'
      preLoaderRoute: typeof FeedPPostIdModalRouteImport
      parentRoute: typeof FeedRoute
    }
    '/$username/p/$postId/modal': {
      id: '/$username/p/$postId/modal'
      path: '/p/$postId/modal'
      fullPath: '/$username/p/$postId/modal'
      preLoaderRoute: typeof UsernamePPostIdModalRouteImport
      parentRoute: typeof UsernameRoute
    }
  }
}

interface UsernameRouteChildren {
  UsernamePPostIdModalRoute: typeof UsernamePPostIdModalRoute
}

const UsernameRouteChildren: UsernameRouteChildren = {
  UsernamePPostIdModalRoute: UsernamePPostIdModalRoute,
}

const UsernameRouteWithChildren = UsernameRoute._addFileChildren(
  UsernameRouteChildren,
)

interface FeedRouteChildren {
  FeedIndexRoute: typeof FeedIndexRoute
  FeedPPostIdModalRoute: typeof FeedPPostIdModalRoute
  FeedStoriesUsernameModalRoute: typeof FeedStoriesUsernameModalRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedIndexRoute: FeedIndexRoute,
  FeedPPostIdModalRoute: FeedPPostIdModalRoute,
  FeedStoriesUsernameModalRoute: FeedStoriesUsernameModalRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

interface DirectRouteChildren {
  DirectConversationIdRoute: typeof DirectConversationIdRoute
  DirectInboxRoute: typeof DirectInboxRoute
  DirectIndexRoute: typeof DirectIndexRoute
}

const DirectRouteChildren: DirectRouteChildren = {
  DirectConversationIdRoute: DirectConversationIdRoute,
  DirectInboxRoute: DirectInboxRoute,
  DirectIndexRoute: DirectIndexRoute,
}

const DirectRouteWithChildren =
  DirectRoute._addFileChildren(DirectRouteChildren)

interface ExploreRouteChildren {
  ExplorePPostIdModalRoute: typeof ExplorePPostIdModalRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExplorePPostIdModalRoute: ExplorePPostIdModalRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountPrivacyRoute: typeof SettingsAccountPrivacyRoute
  SettingsEditProfileRoute: typeof SettingsEditProfileRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsSavedRoute: typeof SettingsSavedRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountPrivacyRoute: SettingsAccountPrivacyRoute,
  SettingsEditProfileRoute: SettingsEditProfileRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsSavedRoute: SettingsSavedRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  UsernameRoute: UsernameRouteWithChildren,
  FeedRoute: FeedRouteWithChildren,
  DirectRoute: DirectRouteWithChildren,
  ExploreRoute: ExploreRouteWithChildren,
  ReelsRoute: ReelsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  PPostIdRoute: PPostIdRoute,
  StoriesUsernameRoute: StoriesUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
